version: '3.3'
services:
    jupyterhub:
        container_name: jupyter
        image: jupyter/datascience-notebook
        user: root
        environment:
            - GRANT_SUDO=yes
        volumes:
            - './data:/home/jovyan'
        command: "jupyter notebook --ip='*' --NotebookApp.token='' --NotebookApp.password=''"